### ISSUE TITLE
Flask.ext not found

### ISSUE THREAD

**Issue by 73696E** [sigilioso/long_polling_example#1]
Can't run, get this even just installed flask

    from flask.ext import restful
ImportError: No module named ext

**Comment by sigilioso** [comment]
This code is pretty old and I've just realized README does not reference to flask-restful version. Try to use a previous version of flask-restful, try `pip install flask-restful==0.2.2`.

When I have a while I'll update README or adapt the code tu run in a recent.

Thanks!

**Comment by sigilioso** [comment]
Fixed in [5a5ea8a9d53e3929aae8059b0bcda6df0ff14633](https://github.com/sigilioso/long_polling_example/commit/5a5ea8a9d53e3929aae8059b0bcda6df0ff14633)
